### ISSUE TITLE
Finalize BLAST

### ISSUE THREAD

**Issue by ctcncgr** [ncgr/HapMap2#2]
Finalize the BLAST service

**Comment by ctcncgr** [comment]
BLAST done as far as demo is concerned.

Now we can do cool things like JBrowse linkouts and alignment displays for each HSP.

Also considering harboring temporary ASN to allow for custom mining.  This is a dream for now

**Comment by adf-ncgr** [comment]
I see we only have protein targets for a couple of the lines. I am sure this is because most of them only came with gff3 files. I plan to use this as an opportunity to push for clarity on requirements for gff3-derived fasta files in the datastore at which time we can enhance the offerings here...

**Comment by ctcncgr** [comment]
Done for now
